site_name: Higher Computing Science
nav:
    - Home: 'index.md'
    - Unit 1 - Software Design and Development:
      - SDD/index.md
      - Development Methodologies: 'SDD/01-Development-Methodologies.md'
      - Analysis:
          - Explanation: 'SDD/2.0-Analysis.md'
          - Functional Requirements: 'SDD/2.1-Functional-Requirements.md'
          - Purpose: 'SDD/2.2-Purpose.md'
          - Scope: 'SDD/2.3-Scope.md'
          - Boundaries: 'SDD/2.4-Boundaries.md'
          - Example Question: 'SDD/2.5-Example-Question.md'
      - Design:
          - Modular Programming: 'SDD/3.1-Modular-Programming.md'  
          - Main Algorithm and Refinements: 'SDD/3.2-Main-Algorithm-and-Refinements.md'
          - Data Flow In Out: 'SDD/3.3-Data-Flow-In-Out.md' 
      - Software Implementation:
          - Software Implementation: 'SDD/04-Software-Implementation.md'
          - Sub-program Procedures: 'SI/01-Sub-Program Procedures.md'
          - Scope of Variables and Parameter Passing: 'SI/02-Scope-of-Variables-and-Parameter-Passing.md'
          - Working with Files: 'SI/05-Working-with-Files-(txt).md'
          - Working with .csv Files: 'SI/06-Working-with-Files-(csv).md'
          - Working with Records: 'SI/07-Working-with-Records.md'
          - Linear Searching: 'SI/08-Standard-Algorithms-Linear-Search.md'
          - Count Occurrences: 'SI/09-Standard-Algorithms-Count-Occurrences.md'
          - Finding Minimum and Maximum: 'SI/10-Standard-Algorithms-Finding-Minimum-and-Maximum.md'
          - Parrallel 1D Arrays: 'SI/11-Parallel-1D-Arrays.md'
          - Arrays of Records: 'SI/12-Arrays-of-Records.md'
    - Unit 2 - Computer Systems:
      - CS/index.md
    - Unit 3 - Database Design and Development:
      - DDD/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  font:
    text: Quicksand
  palette: 
    - scheme: slate
      toggle:
       icon: material/weather-sunny
       name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
       icon: material/weather-night
       name: Light mode
      primary: blue
      accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
