site_name: Higher Computing Science
nav:
    - Home: 'index.md'
    - Unit 1 - Software Design and Development:
      - SDD/index.md
      - Development Methodologies: 'SDD/01-Development-Methodologies.md'
      - Analysis: 'SDD/02-Analysis.md'
      - Design: 'SDD/03-Design.md'
      - Software Implementation: 'SDD/04-Software-Implementation.md'
    - Unit 2 - Software Implementation:
      - SI/index.md
      - Sub-program Procedures: 'SI/01-Sub-Program Procedures.md'
      - Scope of Variables and Parameter Passing: 'SI/02-Scope-of-Variables-and-Parameter-Passing.md'
      - Working with Files: 'SI/05-Working-with-Files-(txt).md'
      - Working with .csv Files: 'SI/06-Working-with-Files-(csv).md'
      - Parrallel 1D Arrays: 'SI/07-Parallel-1D-Arrays.md'
      - Working with Records: 'SI/08-Working-with-Records.md'
    - Unit 3 - Computer Systems:
      - CS/index.md
    - Unit 4 - Database Design and Development:
      - DDD/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: material
  font:
    text: Quicksand
  palette: 
    - scheme: slate
      toggle:
       icon: material/weather-sunny
       name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
       icon: material/weather-night
       name: Light mode
      primary: blue
      accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.expand
    - content.tabs.link
